### ISSUE TITLE
NullReferenceException invoking expression

### ISSUE THREAD

**Issue by genez** [pvginkel/Expressions#14]
I'm stuck with an issue with a test expression that I'm writing:

string translatedString = "uppercase(\"hello\")";
var expr = new DynamicExpression(translatedString, ExpressionLanguage.Csharp);
var context = new ExpressionContext(null, new CustomOwner(), true);
var boundExpression = expr.Bind(context);
object res = boundExpression.Invoke();

At Invoke time, I get a NullRef exception without any useful debug info.
My CustomOwner is as simple as this:

public class CustomOwner
{
        public string uppercase(string str)
        {
            return str.ToUpperInvariant();
        }
}

can you please tell me what I am doing wrong?

thanks

**Comment by pvginkel** [comment]
Thanks very much for your bug report. I've done two things. First, I've created a unit test for your issue. You can see this above this comment. Second, the prolem was that you're using Bind yourself, but shouldn't. You don't have to call Bind. Instead, just call Invoke and pass the context there. The problem was that the Invoke needs the context too, and since you didn't provide one, the owner became null, so the call to uppercase was done on a null reference. I've added an exception which describes this so hopefully for the next person it becomes a bit more obvious what the problem was. If you change your code to the following, it should work:

``` csharp
string translatedString = "uppercase(\"hello\")";
var expr = new DynamicExpression(translatedString, ExpressionLanguage.Csharp);
var context = new ExpressionContext(null, new CustomOwner(), true);
object res = expr.Invoke(context);
```

**Comment by genez** [comment]
Thank you very much, btw I was following examples taken from tha main page of the project :-)

**Comment by pvginkel** [comment]
Bind is for somewhat advanced use cases where you want to cache your expressions. It's not necessary per se. See https://github.com/pvginkel/Expressions#combined-binding-and-invocation for more info on this.

Can you point me to the example you're referring to? I'm not sure since the readme doesn't really has an example like the one you provided.
