### ISSUE TITLE
GetVariableType/GetVariableValue function question

### ISSUE THREAD

**Issue by ifle** [pvginkel/Expressions#15]
Hi,

Suppose I have expression like this A.B.Value.
Result of Value property depended to B type and some logic.
Is there a way to get the B object from GetVariableType/GetVariableValue functions. 
Singature of these functions has variable name only.

Thanks

**Comment by pvginkel** [comment]
I'm not sure what you mean. Could you please give a more expanded example
of what you're trying to accomplish? That may help to answer your question.

**Comment by ifle** [comment]
Thanks for your reply.

```
public class Person
{

}

public class Manager : Person
{        
       public Team Team { get; set; }
}

public class Unit
{
      public Person Manager { get; set; }
}
unit = new Unit {  Manager = new Manager()   };
Expression : unit.Manager.Team
```

If following  "unit.Manager.Team" expression can works, when Manager property is Person type and does not have property Team. 
In FLEE following code does not works

Thanks

**Comment by pvginkel** [comment]
Don't you mean that Manager should inherit from Person? In your example,
this could never work because Manager cannot be assigned to unit.Manager
because Manager does not inherit from Person.

I'm not sure what you're trying to accomplish, but what if you would create
an expression "unit.Manager". Then you can do something like this:
- Execute the "unit.Manager" expression;
- Test whether the result is a Manager instance;
- If so, execute the "unit.Manager.Team" expression.

**Comment by ifle** [comment]
Yes, Manager inherit from Person. I fixed my example.
Following test failed with ExpressionsException : Unresolved identifier 'Team' message. 
I would like resolve Team property by impllement IExpressionContext interface.
But my problem that I haven't access to a last resolved object in expression.
I can't split expression bacause can't change legacy application. 

```
[TestFixture]
public class Class1
{
    [Test]
    public void ExpressionsTest()
    {
        var context = new ExpressionContext();
        context.Variables.Add("unit", new Unit { Manager = new Manager()});
        var e = new DynamicExpression<Team>("unit.Manager.Team", ExpressionLanguage.Flee);
        Debug.WriteLine(e.Invoke(context));
    }


    public class Person
    {
    }

    public class Manager : Person
    {
        public Team Team { get; set; }
    }

    public class Unit
    {
        public Person Manager { get; set; }
    }
}

public class Team
{
}

```

**Comment by pvginkel** [comment]
OK, it's clearer now. I don't think there is an easy solution to this. The expression compiler statically compiles the expression, and since Person doesn't have the Team property, it can't compile it. The main difference here is that Expressions works more like a normal compiler, and the same wouldn't work in C# either.

I could try to figure out what Flee is doing to make this work, but I can't do that at the moment, so right now I don't have a solution for you.

**Comment by ifle** [comment]
In FLEE that does not works too. I understand.
