### ISSUE TITLE
Multiline Expressions

### ISSUE THREAD

**Issue by gsivorot** [pvginkel/Expressions#18]
Is there any way to have multiline expressions evaluated?  I'd like the user to be able to declare a few simple variables inline so their final formula isn't so complicated. Those variables could be dependent on previous variables...

a = 1.5;
b = 5.6;
c = a \* b / 1000;
a + b \* c / a + b;

**Comment by pvginkel** [comment]
Sorry for the late response. This library specifically is an expression compiler. The changes required to support your request would require a huge amount of effort to implement because you're going beyond just simple expressions and are going to require state. This library specifically excludes this scope.

Maybe have a look at Roslyn.
